[package]
name = "bitvec"
version = "1.0.0"
edition = "2021"
include = ["src/**", "python/**", ".cargo/config.toml", "Cargo.toml", "Cargo.lock", "pyproject.toml", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bitvec"
crate-type = ["cdylib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = { version = "0.22", features = ["gil-refs"] }
bv = "0.11.1"

[package.metadata.maturin]
python-source = "python"

[profile.release]
lto = true
opt-level = 3
